# Generated by Django 3.0.4 on 2020-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletext', '0002_auto_20171204_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecategory',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='simplecategory',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='simplecategory',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
