# Generated by Django 2.2.4 on 2019-08-19 04:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20190819_0056'),
        ('categories', '0002_auto_20170217_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrelation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type+', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category+', to='wiki.Article')),
                ('member_articles', models.ManyToManyField(blank=True, related_name='_articlecategory_member_articles_+', related_query_name='categories+', to='wiki.Article')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.ArticleCategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'article category',
                'verbose_name_plural': 'article categories',
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
                'unique_together': {('parent', 'name')},
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
